version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-backend-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGO_URI=mongodb://mongodb:27017/sharedule  # Use service name, not localhost
    networks:
      - my-network
    depends_on:
      - mongodb


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data


networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
