name: CI Pipeline

on:
  push:
    branches:
      - containerization
  pull_request:
    branches:
      - containerization

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker installation
        run: |
          docker --version
          docker-compose --version

      - name: Build Backend Image
        run: |
          docker build ./backend --file ./backend/Dockerfile --tag backend-image:$(date +%s)

      - name: Build Frontend Image
        run: |
          docker build ./frontend --file ./frontend/Dockerfile --tag frontend-image:$(date +%s)

      - name: Run Docker Compose
        run: |
          docker-compose -f ../docker-compose.yml up -d

      - name: Wait for MongoDB to Start
        run: sleep 10

      - name: Run Backend Unit Tests
        run: |
          docker exec my-backend-container ./gradlew test

      - name: Shut Down Docker Compose
        run: |
          docker-compose -f ../docker-compose.yml down
